/**
 *
 *  Courseteacher.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Courseteacher.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::LMS_DB;

const std::string Courseteacher::Cols::_course_id = "course_id";
const std::string Courseteacher::Cols::_teacher_id = "teacher_id";
const std::string Courseteacher::Cols::_role = "role";
const std::vector<std::string> Courseteacher::primaryKeyName = {"course_id","teacher_id"};
const bool Courseteacher::hasPrimaryKey = true;
const std::string Courseteacher::tableName = "courseteacher";

const std::vector<typename Courseteacher::MetaData> Courseteacher::metaData_={
{"course_id","uint32_t","int unsigned",4,0,1,1},
{"teacher_id","uint32_t","int unsigned",4,0,1,1},
{"role","std::string","char(1)",0,0,0,1}
};
const std::string &Courseteacher::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Courseteacher::Courseteacher(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r["course_id"].as<uint32_t>());
        }
        if(!r["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<uint32_t>(r["teacher_id"].as<uint32_t>());
        }
        if(!r["role"].isNull())
        {
            role_=std::make_shared<std::string>(r["role"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            teacherId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            role_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Courseteacher::Courseteacher(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());

        }
    }
}

Courseteacher::Courseteacher(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("teacher_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_id"].asUInt64());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
}

void Courseteacher::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}
                                                                    
void Courseteacher::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_id"].asUInt64());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
}

const uint32_t &Courseteacher::getValueOfCourseId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Courseteacher::getCourseId() const noexcept
{
    return courseId_;
}
void Courseteacher::setCourseId(const uint32_t &pCourseId) noexcept
{
    courseId_ = std::make_shared<uint32_t>(pCourseId);
    dirtyFlag_[0] = true;
}




const uint32_t &Courseteacher::getValueOfTeacherId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(teacherId_)
        return *teacherId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Courseteacher::getTeacherId() const noexcept
{
    return teacherId_;
}
void Courseteacher::setTeacherId(const uint32_t &pTeacherId) noexcept
{
    teacherId_ = std::make_shared<uint32_t>(pTeacherId);
    dirtyFlag_[1] = true;
}




const std::string &Courseteacher::getValueOfRole() const noexcept
{
    const static std::string defaultValue = std::string();
    if(role_)
        return *role_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Courseteacher::getRole() const noexcept
{
    return role_;
}
void Courseteacher::setRole(const std::string &pRole) noexcept
{
    role_ = std::make_shared<std::string>(pRole);
    dirtyFlag_[2] = true;
}
void Courseteacher::setRole(std::string &&pRole) noexcept
{
    role_ = std::make_shared<std::string>(std::move(pRole));
    dirtyFlag_[2] = true;
}




void Courseteacher::updateId(const uint64_t id)
{
}
typename Courseteacher::PrimaryKeyType Courseteacher::getPrimaryKey() const
{
    return std::make_tuple(*courseId_,*teacherId_);
}

const std::vector<std::string> &Courseteacher::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "course_id",
        "teacher_id",
        "role"
    };
    return inCols;
}

void Courseteacher::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Courseteacher::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Courseteacher::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Courseteacher::toJson() const
{
    Json::Value ret;
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    return ret;
}

Json::Value Courseteacher::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[0]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTeacherId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTeacherId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getRole())
            {
                ret[pMasqueradingVector[2]]=getValueOfRole();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    return ret;
}

bool Courseteacher::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, true))
            return false;
    }
    else
    {
        err="The course_id column cannot be null";
        return false;
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(1, "teacher_id", pJson["teacher_id"], err, true))
            return false;
    }
    else
    {
        err="The teacher_id column cannot be null";
        return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(2, "role", pJson["role"], err, true))
            return false;
    }
    else
    {
        err="The role column cannot be null";
        return false;
    }
    return true;
}
bool Courseteacher::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Courseteacher::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(1, "teacher_id", pJson["teacher_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(2, "role", pJson["role"], err, false))
            return false;
    }
    return true;
}
bool Courseteacher::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Courseteacher::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson, 
                                     std::string &err, 
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
