/**
 *
 *  Course.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

using namespace drogon::orm;
namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace LMS_DB 
{

class Course
{
  public:
    struct Cols
    {
        static const std::string _course_id;
        static const std::string _owner_id;
        static const std::string _name;
        static const std::string _code;
        static const std::string _teachercode;
        static const std::string _studentcode;
        static const std::string _objective;
        static const std::string _syllabus;
        static const std::string _evaluationmethod;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = uint32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names, 
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all 
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Course(const Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Course(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Course(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Course() = default;
    
    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson, 
                          std::string &err, 
                          bool isForCreation);

    /**  For column course_id  */
    ///Get the value of the column course_id, returns the default value if the column is null
    const uint32_t &getValueOfCourseId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getCourseId() const noexcept;

    ///Set the value of the column course_id
    void setCourseId(const uint32_t &pCourseId) noexcept;


    /**  For column owner_id  */
    ///Get the value of the column owner_id, returns the default value if the column is null
    const uint32_t &getValueOfOwnerId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getOwnerId() const noexcept;

    ///Set the value of the column owner_id
    void setOwnerId(const uint32_t &pOwnerId) noexcept;


    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;

    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;


    /**  For column code  */
    ///Get the value of the column code, returns the default value if the column is null
    const std::string &getValueOfCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCode() const noexcept;

    ///Set the value of the column code
    void setCode(const std::string &pCode) noexcept;
    void setCode(std::string &&pCode) noexcept;


    /**  For column teachercode  */
    ///Get the value of the column teachercode, returns the default value if the column is null
    const std::string &getValueOfTeachercode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTeachercode() const noexcept;

    ///Set the value of the column teachercode
    void setTeachercode(const std::string &pTeachercode) noexcept;
    void setTeachercode(std::string &&pTeachercode) noexcept;


    /**  For column studentcode  */
    ///Get the value of the column studentcode, returns the default value if the column is null
    const std::string &getValueOfStudentcode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStudentcode() const noexcept;

    ///Set the value of the column studentcode
    void setStudentcode(const std::string &pStudentcode) noexcept;
    void setStudentcode(std::string &&pStudentcode) noexcept;


    /**  For column objective  */
    ///Get the value of the column objective, returns the default value if the column is null
    const std::string &getValueOfObjective() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getObjective() const noexcept;

    ///Set the value of the column objective
    void setObjective(const std::string &pObjective) noexcept;
    void setObjective(std::string &&pObjective) noexcept;
    void setObjectiveToNull() noexcept;


    /**  For column syllabus  */
    ///Get the value of the column syllabus, returns the default value if the column is null
    const std::string &getValueOfSyllabus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSyllabus() const noexcept;

    ///Set the value of the column syllabus
    void setSyllabus(const std::string &pSyllabus) noexcept;
    void setSyllabus(std::string &&pSyllabus) noexcept;
    void setSyllabusToNull() noexcept;


    /**  For column evaluationmethod  */
    ///Get the value of the column evaluationmethod, returns the default value if the column is null
    const std::string &getValueOfEvaluationmethod() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEvaluationmethod() const noexcept;

    ///Set the value of the column evaluationmethod
    void setEvaluationmethod(const std::string &pEvaluationmethod) noexcept;
    void setEvaluationmethod(std::string &&pEvaluationmethod) noexcept;
    void setEvaluationmethodToNull() noexcept;



    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend Mapper<Course>;
#ifdef __cpp_impl_coroutine
    friend CoroMapper<Course>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint32_t> courseId_;
    std::shared_ptr<uint32_t> ownerId_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> code_;
    std::shared_ptr<std::string> teachercode_;
    std::shared_ptr<std::string> studentcode_;
    std::shared_ptr<std::string> objective_;
    std::shared_ptr<std::string> syllabus_;
    std::shared_ptr<std::string> evaluationmethod_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where course_id = ?";
        return sql;                   
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where course_id = ?";
        return sql;                   
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "course_id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "owner_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "code,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "teachercode,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "studentcode,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "objective,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "syllabus,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "evaluationmethod,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";
        
        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        } 
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;   
    }
};
} // namespace LMS_DB
} // namespace drogon_model
