/**
 *
 *  Coursestudymaterial.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Coursestudymaterial.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::LMS_DB;

const std::string Coursestudymaterial::Cols::_course_id = "course_id";
const std::string Coursestudymaterial::Cols::_teacher_id = "teacher_id";
const std::string Coursestudymaterial::Cols::_file_id = "file_id";
const std::string Coursestudymaterial::Cols::_date_created = "date_created";
const std::vector<std::string> Coursestudymaterial::primaryKeyName = {"course_id","teacher_id","file_id"};
const bool Coursestudymaterial::hasPrimaryKey = true;
const std::string Coursestudymaterial::tableName = "coursestudymaterial";

const std::vector<typename Coursestudymaterial::MetaData> Coursestudymaterial::metaData_={
{"course_id","uint32_t","int unsigned",4,0,1,1},
{"teacher_id","uint32_t","int unsigned",4,0,1,1},
{"file_id","uint32_t","int unsigned",4,0,1,1},
{"date_created","std::string","varchar(45)",45,0,0,0}
};
const std::string &Coursestudymaterial::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Coursestudymaterial::Coursestudymaterial(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r["course_id"].as<uint32_t>());
        }
        if(!r["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<uint32_t>(r["teacher_id"].as<uint32_t>());
        }
        if(!r["file_id"].isNull())
        {
            fileId_=std::make_shared<uint32_t>(r["file_id"].as<uint32_t>());
        }
        if(!r["date_created"].isNull())
        {
            dateCreated_=std::make_shared<std::string>(r["date_created"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            teacherId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            fileId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            dateCreated_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Coursestudymaterial::Coursestudymaterial(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            dateCreated_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());

        }
    }
}

Coursestudymaterial::Coursestudymaterial(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("teacher_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_id"].asUInt64());
        }
    }
    if(pJson.isMember("file_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["file_id"].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson["file_id"].asUInt64());
        }
    }
    if(pJson.isMember("date_created"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["date_created"].isNull())
        {
            dateCreated_=std::make_shared<std::string>(pJson["date_created"].asString());
        }
    }
}

void Coursestudymaterial::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            dateCreated_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}
                                                                    
void Coursestudymaterial::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_id"].asUInt64());
        }
    }
    if(pJson.isMember("file_id"))
    {
        if(!pJson["file_id"].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson["file_id"].asUInt64());
        }
    }
    if(pJson.isMember("date_created"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["date_created"].isNull())
        {
            dateCreated_=std::make_shared<std::string>(pJson["date_created"].asString());
        }
    }
}

const uint32_t &Coursestudymaterial::getValueOfCourseId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Coursestudymaterial::getCourseId() const noexcept
{
    return courseId_;
}
void Coursestudymaterial::setCourseId(const uint32_t &pCourseId) noexcept
{
    courseId_ = std::make_shared<uint32_t>(pCourseId);
    dirtyFlag_[0] = true;
}




const uint32_t &Coursestudymaterial::getValueOfTeacherId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(teacherId_)
        return *teacherId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Coursestudymaterial::getTeacherId() const noexcept
{
    return teacherId_;
}
void Coursestudymaterial::setTeacherId(const uint32_t &pTeacherId) noexcept
{
    teacherId_ = std::make_shared<uint32_t>(pTeacherId);
    dirtyFlag_[1] = true;
}




const uint32_t &Coursestudymaterial::getValueOfFileId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(fileId_)
        return *fileId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Coursestudymaterial::getFileId() const noexcept
{
    return fileId_;
}
void Coursestudymaterial::setFileId(const uint32_t &pFileId) noexcept
{
    fileId_ = std::make_shared<uint32_t>(pFileId);
    dirtyFlag_[2] = true;
}




const std::string &Coursestudymaterial::getValueOfDateCreated() const noexcept
{
    const static std::string defaultValue = std::string();
    if(dateCreated_)
        return *dateCreated_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Coursestudymaterial::getDateCreated() const noexcept
{
    return dateCreated_;
}
void Coursestudymaterial::setDateCreated(const std::string &pDateCreated) noexcept
{
    dateCreated_ = std::make_shared<std::string>(pDateCreated);
    dirtyFlag_[3] = true;
}
void Coursestudymaterial::setDateCreated(std::string &&pDateCreated) noexcept
{
    dateCreated_ = std::make_shared<std::string>(std::move(pDateCreated));
    dirtyFlag_[3] = true;
}


void Coursestudymaterial::setDateCreatedToNull() noexcept
{
    dateCreated_.reset();
    dirtyFlag_[3] = true;
}


void Coursestudymaterial::updateId(const uint64_t id)
{
}
typename Coursestudymaterial::PrimaryKeyType Coursestudymaterial::getPrimaryKey() const
{
    return std::make_tuple(*courseId_,*teacherId_,*fileId_);
}

const std::vector<std::string> &Coursestudymaterial::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "course_id",
        "teacher_id",
        "file_id",
        "date_created"
    };
    return inCols;
}

void Coursestudymaterial::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getFileId())
        {
            binder << getValueOfFileId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateCreated())
        {
            binder << getValueOfDateCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Coursestudymaterial::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Coursestudymaterial::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getFileId())
        {
            binder << getValueOfFileId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateCreated())
        {
            binder << getValueOfDateCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Coursestudymaterial::toJson() const
{
    Json::Value ret;
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getFileId())
    {
        ret["file_id"]=getValueOfFileId();
    }
    else
    {
        ret["file_id"]=Json::Value();
    }
    if(getDateCreated())
    {
        ret["date_created"]=getValueOfDateCreated();
    }
    else
    {
        ret["date_created"]=Json::Value();
    }
    return ret;
}

Json::Value Coursestudymaterial::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[0]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTeacherId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTeacherId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getFileId())
            {
                ret[pMasqueradingVector[2]]=getValueOfFileId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDateCreated())
            {
                ret[pMasqueradingVector[3]]=getValueOfDateCreated();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getFileId())
    {
        ret["file_id"]=getValueOfFileId();
    }
    else
    {
        ret["file_id"]=Json::Value();
    }
    if(getDateCreated())
    {
        ret["date_created"]=getValueOfDateCreated();
    }
    else
    {
        ret["date_created"]=Json::Value();
    }
    return ret;
}

bool Coursestudymaterial::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, true))
            return false;
    }
    else
    {
        err="The course_id column cannot be null";
        return false;
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(1, "teacher_id", pJson["teacher_id"], err, true))
            return false;
    }
    else
    {
        err="The teacher_id column cannot be null";
        return false;
    }
    if(pJson.isMember("file_id"))
    {
        if(!validJsonOfField(2, "file_id", pJson["file_id"], err, true))
            return false;
    }
    else
    {
        err="The file_id column cannot be null";
        return false;
    }
    if(pJson.isMember("date_created"))
    {
        if(!validJsonOfField(3, "date_created", pJson["date_created"], err, true))
            return false;
    }
    return true;
}
bool Coursestudymaterial::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Coursestudymaterial::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(1, "teacher_id", pJson["teacher_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("file_id"))
    {
        if(!validJsonOfField(2, "file_id", pJson["file_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("date_created"))
    {
        if(!validJsonOfField(3, "date_created", pJson["date_created"], err, false))
            return false;
    }
    return true;
}
bool Coursestudymaterial::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Coursestudymaterial::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson, 
                                           std::string &err, 
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 45)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 45)";
                return false;               
            }

            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
