/**
 *
 *  Studentcourse.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Studentcourse.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::LMS_DB;

const std::string Studentcourse::Cols::_course_id = "course_id";
const std::string Studentcourse::Cols::_student_id = "student_id";
const std::string Studentcourse::Cols::_status = "status";
const std::string Studentcourse::Cols::_grade = "grade";
const std::vector<std::string> Studentcourse::primaryKeyName = {"course_id","student_id"};
const bool Studentcourse::hasPrimaryKey = true;
const std::string Studentcourse::tableName = "studentcourse";

const std::vector<typename Studentcourse::MetaData> Studentcourse::metaData_={
{"course_id","uint32_t","int unsigned",4,0,1,1},
{"student_id","uint32_t","int unsigned",4,0,1,1},
{"status","std::string","char(1)",0,0,0,0},
{"grade","std::string","varchar(45)",45,0,0,0}
};
const std::string &Studentcourse::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Studentcourse::Studentcourse(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r["course_id"].as<uint32_t>());
        }
        if(!r["student_id"].isNull())
        {
            studentId_=std::make_shared<uint32_t>(r["student_id"].as<uint32_t>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["grade"].isNull())
        {
            grade_=std::make_shared<std::string>(r["grade"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            studentId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            grade_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Studentcourse::Studentcourse(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());

        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            grade_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());

        }
    }
}

Studentcourse::Studentcourse(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("student_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson["student_id"].asUInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("grade"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["grade"].isNull())
        {
            grade_=std::make_shared<std::string>(pJson["grade"].asString());
        }
    }
}

void Studentcourse::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            grade_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}
                                                                    
void Studentcourse::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("student_id"))
    {
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson["student_id"].asUInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("grade"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["grade"].isNull())
        {
            grade_=std::make_shared<std::string>(pJson["grade"].asString());
        }
    }
}

const uint32_t &Studentcourse::getValueOfCourseId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Studentcourse::getCourseId() const noexcept
{
    return courseId_;
}
void Studentcourse::setCourseId(const uint32_t &pCourseId) noexcept
{
    courseId_ = std::make_shared<uint32_t>(pCourseId);
    dirtyFlag_[0] = true;
}




const uint32_t &Studentcourse::getValueOfStudentId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(studentId_)
        return *studentId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Studentcourse::getStudentId() const noexcept
{
    return studentId_;
}
void Studentcourse::setStudentId(const uint32_t &pStudentId) noexcept
{
    studentId_ = std::make_shared<uint32_t>(pStudentId);
    dirtyFlag_[1] = true;
}




const std::string &Studentcourse::getValueOfStatus() const noexcept
{
    const static std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Studentcourse::getStatus() const noexcept
{
    return status_;
}
void Studentcourse::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[2] = true;
}
void Studentcourse::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[2] = true;
}


void Studentcourse::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[2] = true;
}


const std::string &Studentcourse::getValueOfGrade() const noexcept
{
    const static std::string defaultValue = std::string();
    if(grade_)
        return *grade_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Studentcourse::getGrade() const noexcept
{
    return grade_;
}
void Studentcourse::setGrade(const std::string &pGrade) noexcept
{
    grade_ = std::make_shared<std::string>(pGrade);
    dirtyFlag_[3] = true;
}
void Studentcourse::setGrade(std::string &&pGrade) noexcept
{
    grade_ = std::make_shared<std::string>(std::move(pGrade));
    dirtyFlag_[3] = true;
}


void Studentcourse::setGradeToNull() noexcept
{
    grade_.reset();
    dirtyFlag_[3] = true;
}


void Studentcourse::updateId(const uint64_t id)
{
}
typename Studentcourse::PrimaryKeyType Studentcourse::getPrimaryKey() const
{
    return std::make_tuple(*courseId_,*studentId_);
}

const std::vector<std::string> &Studentcourse::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "course_id",
        "student_id",
        "status",
        "grade"
    };
    return inCols;
}

void Studentcourse::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGrade())
        {
            binder << getValueOfGrade();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Studentcourse::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Studentcourse::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGrade())
        {
            binder << getValueOfGrade();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Studentcourse::toJson() const
{
    Json::Value ret;
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getGrade())
    {
        ret["grade"]=getValueOfGrade();
    }
    else
    {
        ret["grade"]=Json::Value();
    }
    return ret;
}

Json::Value Studentcourse::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[0]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStudentId())
            {
                ret[pMasqueradingVector[1]]=getValueOfStudentId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[2]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getGrade())
            {
                ret[pMasqueradingVector[3]]=getValueOfGrade();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getGrade())
    {
        ret["grade"]=getValueOfGrade();
    }
    else
    {
        ret["grade"]=Json::Value();
    }
    return ret;
}

bool Studentcourse::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, true))
            return false;
    }
    else
    {
        err="The course_id column cannot be null";
        return false;
    }
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(1, "student_id", pJson["student_id"], err, true))
            return false;
    }
    else
    {
        err="The student_id column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(2, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("grade"))
    {
        if(!validJsonOfField(3, "grade", pJson["grade"], err, true))
            return false;
    }
    return true;
}
bool Studentcourse::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Studentcourse::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(1, "student_id", pJson["student_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(2, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("grade"))
    {
        if(!validJsonOfField(3, "grade", pJson["grade"], err, false))
            return false;
    }
    return true;
}
bool Studentcourse::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Studentcourse::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson, 
                                     std::string &err, 
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 45)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 45)";
                return false;               
            }

            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
