/**
 *
 *  LmsCourseController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsCourseControllerBase.h"

#include "../models/Course.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the course table.
 */

class LmsCourseController: public drogon::HttpController<LmsCourseController>, public LmsCourseControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsCourseController::getOne,"/course/{1}",Get,Options);
    ADD_METHOD_TO(LmsCourseController::updateOne,"/course/{1}",Put,Options);
    ADD_METHOD_TO(LmsCourseController::deleteOne,"/course/{1}",Delete,Options);
    ADD_METHOD_TO(LmsCourseController::get,"/course",Get,Options);
    ADD_METHOD_TO(LmsCourseController::create,"/course",Post,Options);
    //ADD_METHOD_TO(LmsCourseController::update,"/course",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Course::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Course::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Course::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
