/**
 *
 *  LmsCoursestudymaterialController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsCoursestudymaterialControllerBase.h"

#include "../models/Coursestudymaterial.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the coursestudymaterial table.
 */

class LmsCoursestudymaterialController: public drogon::HttpController<LmsCoursestudymaterialController>, public LmsCoursestudymaterialControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsCoursestudymaterialController::get,"/coursestudymaterial",Get,Options);
    ADD_METHOD_TO(LmsCoursestudymaterialController::create,"/coursestudymaterial",Post,Options);
    //ADD_METHOD_TO(LmsCoursestudymaterialController::update,"/coursestudymaterial",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
