/**
 *
 *  LmsDepartmentController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsDepartmentControllerBase.h"

#include "../models/Department.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the department table.
 */

class LmsDepartmentController: public drogon::HttpController<LmsDepartmentController>, public LmsDepartmentControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsDepartmentController::getOne,"/department/{1}",Get,Options);
    ADD_METHOD_TO(LmsDepartmentController::updateOne,"/department/{1}",Put,Options);
    ADD_METHOD_TO(LmsDepartmentController::deleteOne,"/department/{1}",Delete,Options);
    ADD_METHOD_TO(LmsDepartmentController::get,"/department",Get,Options);
    ADD_METHOD_TO(LmsDepartmentController::create,"/department",Post,Options);
    //ADD_METHOD_TO(LmsDepartmentController::update,"/department",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Department::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Department::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Department::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
