/**
 *
 *  LmsFilesController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsFilesControllerBase.h"

#include "../models/Files.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the files table.
 */

class LmsFilesController: public drogon::HttpController<LmsFilesController>, public LmsFilesControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsFilesController::getOne,"/files/{1}",Get,Options);
    ADD_METHOD_TO(LmsFilesController::updateOne,"/files/{1}",Put,Options);
    ADD_METHOD_TO(LmsFilesController::deleteOne,"/files/{1}",Delete,Options);
    ADD_METHOD_TO(LmsFilesController::get,"/files",Get,Options);
    ADD_METHOD_TO(LmsFilesController::create,"/files",Post,Options);
    //ADD_METHOD_TO(LmsFilesController::update,"/files",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Files::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Files::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Files::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
