/**
 *
 *  LmsUsersController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsUsersController.h"
#include <string>





void LmsUsersController::getOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Users::PrimaryKeyType &&id)
{
    LmsUsersControllerBase::getOne(req, std::move(callback), std::move(id));
}


void LmsUsersController::updateOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Users::PrimaryKeyType &&id)
{
    LmsUsersControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void LmsUsersController::deleteOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Users::PrimaryKeyType &&id)
{
    LmsUsersControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void LmsUsersController::get(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsUsersControllerBase::get(req, std::move(callback));
}

void LmsUsersController::create(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsUsersControllerBase::create(req, std::move(callback));
}
