/**
 *
 *  LmsAssignmentController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsAssignmentController.h"
#include <string>






void LmsAssignmentController::get(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsAssignmentControllerBase::get(req, std::move(callback));
}

void LmsAssignmentController::create(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsAssignmentControllerBase::create(req, std::move(callback));
}
