/**
 *
 *  LmsAssignmentController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsAssignmentControllerBase.h"

#include "../models/Assignment.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the assignment table.
 */

class LmsAssignmentController: public drogon::HttpController<LmsAssignmentController>, public LmsAssignmentControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsAssignmentController::get,"/assignment",Get,Options);
    ADD_METHOD_TO(LmsAssignmentController::create,"/assignment",Post,Options);
    //ADD_METHOD_TO(LmsAssignmentController::update,"/assignment",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
