/**
 *
 *  LmsCourseController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsCourseController.h"
#include <string>





void LmsCourseController::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Course::PrimaryKeyType &&id)
{
    LmsCourseControllerBase::getOne(req, std::move(callback), std::move(id));
}


void LmsCourseController::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Course::PrimaryKeyType &&id)
{
    LmsCourseControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void LmsCourseController::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Course::PrimaryKeyType &&id)
{
    LmsCourseControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void LmsCourseController::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsCourseControllerBase::get(req, std::move(callback));
}

void LmsCourseController::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsCourseControllerBase::create(req, std::move(callback));
}
