/**
 *
 *  LmsCoursestudymaterialController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsCoursestudymaterialController.h"
#include <string>






void LmsCoursestudymaterialController::get(const HttpRequestPtr &req,
                                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsCoursestudymaterialControllerBase::get(req, std::move(callback));
}

void LmsCoursestudymaterialController::create(const HttpRequestPtr &req,
                                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsCoursestudymaterialControllerBase::create(req, std::move(callback));
}
