/**
 *
 *  LmsCourseteacherController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsCourseteacherControllerBase.h"

#include "../models/Courseteacher.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the courseteacher table.
 */

class LmsCourseteacherController: public drogon::HttpController<LmsCourseteacherController>, public LmsCourseteacherControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsCourseteacherController::get,"/courseteacher",Get,Options);
    ADD_METHOD_TO(LmsCourseteacherController::create,"/courseteacher",Post,Options);
    //ADD_METHOD_TO(LmsCourseteacherController::update,"/courseteacher",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
