/**
 *
 *  LmsCourseteacherController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsCourseteacherController.h"
#include <string>






void LmsCourseteacherController::get(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsCourseteacherControllerBase::get(req, std::move(callback));
}

void LmsCourseteacherController::create(const HttpRequestPtr &req,
                                        std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsCourseteacherControllerBase::create(req, std::move(callback));
}
