/**
 *
 *  LmsDepartmentController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsDepartmentController.h"
#include <string>





void LmsDepartmentController::getOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Department::PrimaryKeyType &&id)
{
    LmsDepartmentControllerBase::getOne(req, std::move(callback), std::move(id));
}


void LmsDepartmentController::updateOne(const HttpRequestPtr &req,
                                        std::function<void(const HttpResponsePtr &)> &&callback,
                                        Department::PrimaryKeyType &&id)
{
    LmsDepartmentControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void LmsDepartmentController::deleteOne(const HttpRequestPtr &req,
                                        std::function<void(const HttpResponsePtr &)> &&callback,
                                        Department::PrimaryKeyType &&id)
{
    LmsDepartmentControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void LmsDepartmentController::get(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsDepartmentControllerBase::get(req, std::move(callback));
}

void LmsDepartmentController::create(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsDepartmentControllerBase::create(req, std::move(callback));
}
