/**
 *
 *  LmsFilesController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsFilesController.h"
#include <string>





void LmsFilesController::getOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Files::PrimaryKeyType &&id)
{
    LmsFilesControllerBase::getOne(req, std::move(callback), std::move(id));
}


void LmsFilesController::updateOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Files::PrimaryKeyType &&id)
{
    LmsFilesControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void LmsFilesController::deleteOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Files::PrimaryKeyType &&id)
{
    LmsFilesControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void LmsFilesController::get(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsFilesControllerBase::get(req, std::move(callback));
}

void LmsFilesController::create(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsFilesControllerBase::create(req, std::move(callback));
}
