/**
 *
 *  LmsStudentcourseController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsStudentcourseControllerBase.h"

#include "../models/Studentcourse.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the studentcourse table.
 */

class LmsStudentcourseController: public drogon::HttpController<LmsStudentcourseController>, public LmsStudentcourseControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsStudentcourseController::get,"/studentcourse",Get,Options);
    ADD_METHOD_TO(LmsStudentcourseController::create,"/studentcourse",Post,Options);
    //ADD_METHOD_TO(LmsStudentcourseController::update,"/studentcourse",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
