/**
 *
 *  LmsStudentcourseController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "LmsStudentcourseController.h"
#include <string>






void LmsStudentcourseController::get(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsStudentcourseControllerBase::get(req, std::move(callback));
}

void LmsStudentcourseController::create(const HttpRequestPtr &req,
                                        std::function<void(const HttpResponsePtr &)> &&callback)
{
    LmsStudentcourseControllerBase::create(req, std::move(callback));
}
