/**
 *
 *  LmsUsersController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "LmsUsersControllerBase.h"

#include "../models/Users.h"
using namespace drogon;

using namespace drogon_model::LMS_DB;

/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the users table.
 */

class LmsUsersController: public drogon::HttpController<LmsUsersController>, public LmsUsersControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(LmsUsersController::getOne,"/users/{1}",Get,Options);
    ADD_METHOD_TO(LmsUsersController::updateOne,"/users/{1}",Put,Options);
    ADD_METHOD_TO(LmsUsersController::deleteOne,"/users/{1}",Delete,Options);
    ADD_METHOD_TO(LmsUsersController::get,"/users",Get,Options);
    ADD_METHOD_TO(LmsUsersController::create,"/users",Post,Options);
    //ADD_METHOD_TO(LmsUsersController::update,"/users",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Users::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Users::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Users::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
