/**
 *
 *  Assignment.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

using namespace drogon::orm;
namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace LMS_DB 
{

class Assignment
{
  public:
    struct Cols
    {
        static const std::string _student_id;
        static const std::string _course_id;
        static const std::string _teacher_created;
        static const std::string _assignment_no;
        static const std::string _file_id;
        static const std::string _deadline;
        static const std::string _status;
        static const std::string _submission_date;
        static const std::string _teacher_corrected;
        static const std::string _marks_awarded;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::vector<std::string> primaryKeyName;
    using PrimaryKeyType = std::tuple<uint32_t,uint32_t,uint32_t,uint32_t>;//student_id,course_id,teacher_created,assignment_no
    PrimaryKeyType getPrimaryKey() const; 

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names, 
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all 
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Assignment(const Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Assignment(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Assignment(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Assignment() = default;
    
    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson, 
                          std::string &err, 
                          bool isForCreation);

    /**  For column student_id  */
    ///Get the value of the column student_id, returns the default value if the column is null
    const uint32_t &getValueOfStudentId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getStudentId() const noexcept;

    ///Set the value of the column student_id
    void setStudentId(const uint32_t &pStudentId) noexcept;


    /**  For column course_id  */
    ///Get the value of the column course_id, returns the default value if the column is null
    const uint32_t &getValueOfCourseId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getCourseId() const noexcept;

    ///Set the value of the column course_id
    void setCourseId(const uint32_t &pCourseId) noexcept;


    /**  For column teacher_created  */
    ///Get the value of the column teacher_created, returns the default value if the column is null
    const uint32_t &getValueOfTeacherCreated() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getTeacherCreated() const noexcept;

    ///Set the value of the column teacher_created
    void setTeacherCreated(const uint32_t &pTeacherCreated) noexcept;


    /**  For column assignment_no  */
    ///Get the value of the column assignment_no, returns the default value if the column is null
    const uint32_t &getValueOfAssignmentNo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getAssignmentNo() const noexcept;

    ///Set the value of the column assignment_no
    void setAssignmentNo(const uint32_t &pAssignmentNo) noexcept;


    /**  For column file_id  */
    ///Get the value of the column file_id, returns the default value if the column is null
    const uint32_t &getValueOfFileId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getFileId() const noexcept;

    ///Set the value of the column file_id
    void setFileId(const uint32_t &pFileId) noexcept;


    /**  For column deadline  */
    ///Get the value of the column deadline, returns the default value if the column is null
    const ::trantor::Date &getValueOfDeadline() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDeadline() const noexcept;

    ///Set the value of the column deadline
    void setDeadline(const ::trantor::Date &pDeadline) noexcept;
    void setDeadlineToNull() noexcept;


    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const std::string &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatus() const noexcept;

    ///Set the value of the column status
    void setStatus(const std::string &pStatus) noexcept;
    void setStatus(std::string &&pStatus) noexcept;
    void setStatusToNull() noexcept;


    /**  For column submission_date  */
    ///Get the value of the column submission_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfSubmissionDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getSubmissionDate() const noexcept;

    ///Set the value of the column submission_date
    void setSubmissionDate(const ::trantor::Date &pSubmissionDate) noexcept;
    void setSubmissionDateToNull() noexcept;


    /**  For column teacher_corrected  */
    ///Get the value of the column teacher_corrected, returns the default value if the column is null
    const uint32_t &getValueOfTeacherCorrected() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint32_t> &getTeacherCorrected() const noexcept;

    ///Set the value of the column teacher_corrected
    void setTeacherCorrected(const uint32_t &pTeacherCorrected) noexcept;


    /**  For column marks_awarded  */
    ///Get the value of the column marks_awarded, returns the default value if the column is null
    const int32_t &getValueOfMarksAwarded() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMarksAwarded() const noexcept;

    ///Set the value of the column marks_awarded
    void setMarksAwarded(const int32_t &pMarksAwarded) noexcept;
    void setMarksAwardedToNull() noexcept;



    static size_t getColumnNumber() noexcept {  return 10;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend Mapper<Assignment>;
#ifdef __cpp_impl_coroutine
    friend CoroMapper<Assignment>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint32_t> studentId_;
    std::shared_ptr<uint32_t> courseId_;
    std::shared_ptr<uint32_t> teacherCreated_;
    std::shared_ptr<uint32_t> assignmentNo_;
    std::shared_ptr<uint32_t> fileId_;
    std::shared_ptr<::trantor::Date> deadline_;
    std::shared_ptr<std::string> status_;
    std::shared_ptr<::trantor::Date> submissionDate_;
    std::shared_ptr<uint32_t> teacherCorrected_;
    std::shared_ptr<int32_t> marksAwarded_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[10]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where student_id = ? and course_id = ? and teacher_created = ? and assignment_no = ?";
        return sql;                   
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where student_id = ? and course_id = ? and teacher_created = ? and assignment_no = ?";
        return sql;                   
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "student_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "course_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "teacher_created,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "assignment_no,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "file_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "deadline,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "status,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "submission_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "teacher_corrected,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "marks_awarded,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";
        
        if(dirtyFlag_[0])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        } 
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;   
    }
};
} // namespace LMS_DB
} // namespace drogon_model
