/**
 *
 *  Assignment.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Assignment.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::LMS_DB;

const std::string Assignment::Cols::_student_id = "student_id";
const std::string Assignment::Cols::_course_id = "course_id";
const std::string Assignment::Cols::_teacher_created = "teacher_created";
const std::string Assignment::Cols::_assignment_no = "assignment_no";
const std::string Assignment::Cols::_file_id = "file_id";
const std::string Assignment::Cols::_deadline = "deadline";
const std::string Assignment::Cols::_status = "status";
const std::string Assignment::Cols::_submission_date = "submission_date";
const std::string Assignment::Cols::_teacher_corrected = "teacher_corrected";
const std::string Assignment::Cols::_marks_awarded = "marks_awarded";
const std::vector<std::string> Assignment::primaryKeyName = {"student_id","course_id","teacher_created","assignment_no"};
const bool Assignment::hasPrimaryKey = true;
const std::string Assignment::tableName = "assignment";

const std::vector<typename Assignment::MetaData> Assignment::metaData_={
{"student_id","uint32_t","int unsigned",4,0,1,1},
{"course_id","uint32_t","int unsigned",4,0,1,1},
{"teacher_created","uint32_t","int unsigned",4,0,1,1},
{"assignment_no","uint32_t","int unsigned",4,0,1,1},
{"file_id","uint32_t","int unsigned",4,0,0,1},
{"deadline","::trantor::Date","date",0,0,0,0},
{"status","std::string","char(1)",0,0,0,0},
{"submission_date","::trantor::Date","date",0,0,0,0},
{"teacher_corrected","uint32_t","int unsigned",4,0,0,1},
{"marks_awarded","int32_t","int",4,0,0,0}
};
const std::string &Assignment::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Assignment::Assignment(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["student_id"].isNull())
        {
            studentId_=std::make_shared<uint32_t>(r["student_id"].as<uint32_t>());
        }
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r["course_id"].as<uint32_t>());
        }
        if(!r["teacher_created"].isNull())
        {
            teacherCreated_=std::make_shared<uint32_t>(r["teacher_created"].as<uint32_t>());
        }
        if(!r["assignment_no"].isNull())
        {
            assignmentNo_=std::make_shared<uint32_t>(r["assignment_no"].as<uint32_t>());
        }
        if(!r["file_id"].isNull())
        {
            fileId_=std::make_shared<uint32_t>(r["file_id"].as<uint32_t>());
        }
        if(!r["deadline"].isNull())
        {
            auto daysStr = r["deadline"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            deadline_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["submission_date"].isNull())
        {
            auto daysStr = r["submission_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submissionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["teacher_corrected"].isNull())
        {
            teacherCorrected_=std::make_shared<uint32_t>(r["teacher_corrected"].as<uint32_t>());
        }
        if(!r["marks_awarded"].isNull())
        {
            marksAwarded_=std::make_shared<int32_t>(r["marks_awarded"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            studentId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            teacherCreated_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            assignmentNo_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            fileId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            deadline_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submissionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            teacherCorrected_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            marksAwarded_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Assignment::Assignment(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            teacherCreated_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            assignmentNo_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[4]].asUInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            deadline_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());

        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submissionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            teacherCorrected_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[8]].asUInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            marksAwarded_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
}

Assignment::Assignment(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("student_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson["student_id"].asUInt64());
        }
    }
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("teacher_created"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["teacher_created"].isNull())
        {
            teacherCreated_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_created"].asUInt64());
        }
    }
    if(pJson.isMember("assignment_no"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["assignment_no"].isNull())
        {
            assignmentNo_=std::make_shared<uint32_t>((uint32_t)pJson["assignment_no"].asUInt64());
        }
    }
    if(pJson.isMember("file_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["file_id"].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson["file_id"].asUInt64());
        }
    }
    if(pJson.isMember("deadline"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["deadline"].isNull())
        {
            auto daysStr = pJson["deadline"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            deadline_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("submission_date"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["submission_date"].isNull())
        {
            auto daysStr = pJson["submission_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submissionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("teacher_corrected"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["teacher_corrected"].isNull())
        {
            teacherCorrected_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_corrected"].asUInt64());
        }
    }
    if(pJson.isMember("marks_awarded"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["marks_awarded"].isNull())
        {
            marksAwarded_=std::make_shared<int32_t>((int32_t)pJson["marks_awarded"].asInt64());
        }
    }
}

void Assignment::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            teacherCreated_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            assignmentNo_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[4]].asUInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            deadline_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submissionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            teacherCorrected_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[8]].asUInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            marksAwarded_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
}
                                                                    
void Assignment::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("student_id"))
    {
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<uint32_t>((uint32_t)pJson["student_id"].asUInt64());
        }
    }
    if(pJson.isMember("course_id"))
    {
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("teacher_created"))
    {
        if(!pJson["teacher_created"].isNull())
        {
            teacherCreated_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_created"].asUInt64());
        }
    }
    if(pJson.isMember("assignment_no"))
    {
        if(!pJson["assignment_no"].isNull())
        {
            assignmentNo_=std::make_shared<uint32_t>((uint32_t)pJson["assignment_no"].asUInt64());
        }
    }
    if(pJson.isMember("file_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["file_id"].isNull())
        {
            fileId_=std::make_shared<uint32_t>((uint32_t)pJson["file_id"].asUInt64());
        }
    }
    if(pJson.isMember("deadline"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["deadline"].isNull())
        {
            auto daysStr = pJson["deadline"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            deadline_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("submission_date"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["submission_date"].isNull())
        {
            auto daysStr = pJson["submission_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            submissionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("teacher_corrected"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["teacher_corrected"].isNull())
        {
            teacherCorrected_=std::make_shared<uint32_t>((uint32_t)pJson["teacher_corrected"].asUInt64());
        }
    }
    if(pJson.isMember("marks_awarded"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["marks_awarded"].isNull())
        {
            marksAwarded_=std::make_shared<int32_t>((int32_t)pJson["marks_awarded"].asInt64());
        }
    }
}

const uint32_t &Assignment::getValueOfStudentId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(studentId_)
        return *studentId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Assignment::getStudentId() const noexcept
{
    return studentId_;
}
void Assignment::setStudentId(const uint32_t &pStudentId) noexcept
{
    studentId_ = std::make_shared<uint32_t>(pStudentId);
    dirtyFlag_[0] = true;
}




const uint32_t &Assignment::getValueOfCourseId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Assignment::getCourseId() const noexcept
{
    return courseId_;
}
void Assignment::setCourseId(const uint32_t &pCourseId) noexcept
{
    courseId_ = std::make_shared<uint32_t>(pCourseId);
    dirtyFlag_[1] = true;
}




const uint32_t &Assignment::getValueOfTeacherCreated() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(teacherCreated_)
        return *teacherCreated_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Assignment::getTeacherCreated() const noexcept
{
    return teacherCreated_;
}
void Assignment::setTeacherCreated(const uint32_t &pTeacherCreated) noexcept
{
    teacherCreated_ = std::make_shared<uint32_t>(pTeacherCreated);
    dirtyFlag_[2] = true;
}




const uint32_t &Assignment::getValueOfAssignmentNo() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(assignmentNo_)
        return *assignmentNo_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Assignment::getAssignmentNo() const noexcept
{
    return assignmentNo_;
}
void Assignment::setAssignmentNo(const uint32_t &pAssignmentNo) noexcept
{
    assignmentNo_ = std::make_shared<uint32_t>(pAssignmentNo);
    dirtyFlag_[3] = true;
}




const uint32_t &Assignment::getValueOfFileId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(fileId_)
        return *fileId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Assignment::getFileId() const noexcept
{
    return fileId_;
}
void Assignment::setFileId(const uint32_t &pFileId) noexcept
{
    fileId_ = std::make_shared<uint32_t>(pFileId);
    dirtyFlag_[4] = true;
}




const ::trantor::Date &Assignment::getValueOfDeadline() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(deadline_)
        return *deadline_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Assignment::getDeadline() const noexcept
{
    return deadline_;
}
void Assignment::setDeadline(const ::trantor::Date &pDeadline) noexcept
{
    deadline_ = std::make_shared<::trantor::Date>(pDeadline.roundDay());
    dirtyFlag_[5] = true;
}


void Assignment::setDeadlineToNull() noexcept
{
    deadline_.reset();
    dirtyFlag_[5] = true;
}


const std::string &Assignment::getValueOfStatus() const noexcept
{
    const static std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Assignment::getStatus() const noexcept
{
    return status_;
}
void Assignment::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[6] = true;
}
void Assignment::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[6] = true;
}


void Assignment::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[6] = true;
}


const ::trantor::Date &Assignment::getValueOfSubmissionDate() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(submissionDate_)
        return *submissionDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Assignment::getSubmissionDate() const noexcept
{
    return submissionDate_;
}
void Assignment::setSubmissionDate(const ::trantor::Date &pSubmissionDate) noexcept
{
    submissionDate_ = std::make_shared<::trantor::Date>(pSubmissionDate.roundDay());
    dirtyFlag_[7] = true;
}


void Assignment::setSubmissionDateToNull() noexcept
{
    submissionDate_.reset();
    dirtyFlag_[7] = true;
}


const uint32_t &Assignment::getValueOfTeacherCorrected() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(teacherCorrected_)
        return *teacherCorrected_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Assignment::getTeacherCorrected() const noexcept
{
    return teacherCorrected_;
}
void Assignment::setTeacherCorrected(const uint32_t &pTeacherCorrected) noexcept
{
    teacherCorrected_ = std::make_shared<uint32_t>(pTeacherCorrected);
    dirtyFlag_[8] = true;
}




const int32_t &Assignment::getValueOfMarksAwarded() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(marksAwarded_)
        return *marksAwarded_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Assignment::getMarksAwarded() const noexcept
{
    return marksAwarded_;
}
void Assignment::setMarksAwarded(const int32_t &pMarksAwarded) noexcept
{
    marksAwarded_ = std::make_shared<int32_t>(pMarksAwarded);
    dirtyFlag_[9] = true;
}


void Assignment::setMarksAwardedToNull() noexcept
{
    marksAwarded_.reset();
    dirtyFlag_[9] = true;
}


void Assignment::updateId(const uint64_t id)
{
}
typename Assignment::PrimaryKeyType Assignment::getPrimaryKey() const
{
    return std::make_tuple(*studentId_,*courseId_,*teacherCreated_,*assignmentNo_);
}

const std::vector<std::string> &Assignment::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "student_id",
        "course_id",
        "teacher_created",
        "assignment_no",
        "file_id",
        "deadline",
        "status",
        "submission_date",
        "teacher_corrected",
        "marks_awarded"
    };
    return inCols;
}

void Assignment::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTeacherCreated())
        {
            binder << getValueOfTeacherCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAssignmentNo())
        {
            binder << getValueOfAssignmentNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getFileId())
        {
            binder << getValueOfFileId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDeadline())
        {
            binder << getValueOfDeadline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSubmissionDate())
        {
            binder << getValueOfSubmissionDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getTeacherCorrected())
        {
            binder << getValueOfTeacherCorrected();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getMarksAwarded())
        {
            binder << getValueOfMarksAwarded();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Assignment::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void Assignment::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getCourseId())
        {
            binder << getValueOfCourseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTeacherCreated())
        {
            binder << getValueOfTeacherCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAssignmentNo())
        {
            binder << getValueOfAssignmentNo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getFileId())
        {
            binder << getValueOfFileId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDeadline())
        {
            binder << getValueOfDeadline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSubmissionDate())
        {
            binder << getValueOfSubmissionDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getTeacherCorrected())
        {
            binder << getValueOfTeacherCorrected();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getMarksAwarded())
        {
            binder << getValueOfMarksAwarded();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Assignment::toJson() const
{
    Json::Value ret;
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getTeacherCreated())
    {
        ret["teacher_created"]=getValueOfTeacherCreated();
    }
    else
    {
        ret["teacher_created"]=Json::Value();
    }
    if(getAssignmentNo())
    {
        ret["assignment_no"]=getValueOfAssignmentNo();
    }
    else
    {
        ret["assignment_no"]=Json::Value();
    }
    if(getFileId())
    {
        ret["file_id"]=getValueOfFileId();
    }
    else
    {
        ret["file_id"]=Json::Value();
    }
    if(getDeadline())
    {
        ret["deadline"]=getDeadline()->toDbStringLocal();
    }
    else
    {
        ret["deadline"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getSubmissionDate())
    {
        ret["submission_date"]=getSubmissionDate()->toDbStringLocal();
    }
    else
    {
        ret["submission_date"]=Json::Value();
    }
    if(getTeacherCorrected())
    {
        ret["teacher_corrected"]=getValueOfTeacherCorrected();
    }
    else
    {
        ret["teacher_corrected"]=Json::Value();
    }
    if(getMarksAwarded())
    {
        ret["marks_awarded"]=getValueOfMarksAwarded();
    }
    else
    {
        ret["marks_awarded"]=Json::Value();
    }
    return ret;
}

Json::Value Assignment::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getStudentId())
            {
                ret[pMasqueradingVector[0]]=getValueOfStudentId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[1]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTeacherCreated())
            {
                ret[pMasqueradingVector[2]]=getValueOfTeacherCreated();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getAssignmentNo())
            {
                ret[pMasqueradingVector[3]]=getValueOfAssignmentNo();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getFileId())
            {
                ret[pMasqueradingVector[4]]=getValueOfFileId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getDeadline())
            {
                ret[pMasqueradingVector[5]]=getDeadline()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[6]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getSubmissionDate())
            {
                ret[pMasqueradingVector[7]]=getSubmissionDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getTeacherCorrected())
            {
                ret[pMasqueradingVector[8]]=getValueOfTeacherCorrected();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getMarksAwarded())
            {
                ret[pMasqueradingVector[9]]=getValueOfMarksAwarded();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getTeacherCreated())
    {
        ret["teacher_created"]=getValueOfTeacherCreated();
    }
    else
    {
        ret["teacher_created"]=Json::Value();
    }
    if(getAssignmentNo())
    {
        ret["assignment_no"]=getValueOfAssignmentNo();
    }
    else
    {
        ret["assignment_no"]=Json::Value();
    }
    if(getFileId())
    {
        ret["file_id"]=getValueOfFileId();
    }
    else
    {
        ret["file_id"]=Json::Value();
    }
    if(getDeadline())
    {
        ret["deadline"]=getDeadline()->toDbStringLocal();
    }
    else
    {
        ret["deadline"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getSubmissionDate())
    {
        ret["submission_date"]=getSubmissionDate()->toDbStringLocal();
    }
    else
    {
        ret["submission_date"]=Json::Value();
    }
    if(getTeacherCorrected())
    {
        ret["teacher_corrected"]=getValueOfTeacherCorrected();
    }
    else
    {
        ret["teacher_corrected"]=Json::Value();
    }
    if(getMarksAwarded())
    {
        ret["marks_awarded"]=getValueOfMarksAwarded();
    }
    else
    {
        ret["marks_awarded"]=Json::Value();
    }
    return ret;
}

bool Assignment::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(0, "student_id", pJson["student_id"], err, true))
            return false;
    }
    else
    {
        err="The student_id column cannot be null";
        return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(1, "course_id", pJson["course_id"], err, true))
            return false;
    }
    else
    {
        err="The course_id column cannot be null";
        return false;
    }
    if(pJson.isMember("teacher_created"))
    {
        if(!validJsonOfField(2, "teacher_created", pJson["teacher_created"], err, true))
            return false;
    }
    else
    {
        err="The teacher_created column cannot be null";
        return false;
    }
    if(pJson.isMember("assignment_no"))
    {
        if(!validJsonOfField(3, "assignment_no", pJson["assignment_no"], err, true))
            return false;
    }
    else
    {
        err="The assignment_no column cannot be null";
        return false;
    }
    if(pJson.isMember("file_id"))
    {
        if(!validJsonOfField(4, "file_id", pJson["file_id"], err, true))
            return false;
    }
    else
    {
        err="The file_id column cannot be null";
        return false;
    }
    if(pJson.isMember("deadline"))
    {
        if(!validJsonOfField(5, "deadline", pJson["deadline"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("submission_date"))
    {
        if(!validJsonOfField(7, "submission_date", pJson["submission_date"], err, true))
            return false;
    }
    if(pJson.isMember("teacher_corrected"))
    {
        if(!validJsonOfField(8, "teacher_corrected", pJson["teacher_corrected"], err, true))
            return false;
    }
    else
    {
        err="The teacher_corrected column cannot be null";
        return false;
    }
    if(pJson.isMember("marks_awarded"))
    {
        if(!validJsonOfField(9, "marks_awarded", pJson["marks_awarded"], err, true))
            return false;
    }
    return true;
}
bool Assignment::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Assignment::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(0, "student_id", pJson["student_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(1, "course_id", pJson["course_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("teacher_created"))
    {
        if(!validJsonOfField(2, "teacher_created", pJson["teacher_created"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("assignment_no"))
    {
        if(!validJsonOfField(3, "assignment_no", pJson["assignment_no"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("file_id"))
    {
        if(!validJsonOfField(4, "file_id", pJson["file_id"], err, false))
            return false;
    }
    if(pJson.isMember("deadline"))
    {
        if(!validJsonOfField(5, "deadline", pJson["deadline"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("submission_date"))
    {
        if(!validJsonOfField(7, "submission_date", pJson["submission_date"], err, false))
            return false;
    }
    if(pJson.isMember("teacher_corrected"))
    {
        if(!validJsonOfField(8, "teacher_corrected", pJson["teacher_corrected"], err, false))
            return false;
    }
    if(pJson.isMember("marks_awarded"))
    {
        if(!validJsonOfField(9, "marks_awarded", pJson["marks_awarded"], err, false))
            return false;
    }
    return true;
}
bool Assignment::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Assignment::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson, 
                                  std::string &err, 
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
