/**
 *
 *  Course.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Course.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::LMS_DB;

const std::string Course::Cols::_course_id = "course_id";
const std::string Course::Cols::_owner_id = "owner_id";
const std::string Course::Cols::_name = "name";
const std::string Course::Cols::_code = "code";
const std::string Course::Cols::_teachercode = "teachercode";
const std::string Course::Cols::_studentcode = "studentcode";
const std::string Course::Cols::_objective = "objective";
const std::string Course::Cols::_syllabus = "syllabus";
const std::string Course::Cols::_evaluationmethod = "evaluationmethod";
const std::string Course::primaryKeyName = "course_id";
const bool Course::hasPrimaryKey = true;
const std::string Course::tableName = "course";

const std::vector<typename Course::MetaData> Course::metaData_={
{"course_id","uint32_t","int unsigned",4,1,1,1},
{"owner_id","uint32_t","int unsigned",4,0,0,1},
{"name","std::string","varchar(40)",40,0,0,1},
{"code","std::string","char(8)",0,0,0,1},
{"teachercode","std::string","char(8)",0,0,0,1},
{"studentcode","std::string","char(8)",0,0,0,1},
{"objective","std::string","varchar(75)",75,0,0,0},
{"syllabus","std::string","varchar(100)",100,0,0,0},
{"evaluationmethod","std::string","varchar(45)",45,0,0,0}
};
const std::string &Course::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Course::Course(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r["course_id"].as<uint32_t>());
        }
        if(!r["owner_id"].isNull())
        {
            ownerId_=std::make_shared<uint32_t>(r["owner_id"].as<uint32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["code"].isNull())
        {
            code_=std::make_shared<std::string>(r["code"].as<std::string>());
        }
        if(!r["teachercode"].isNull())
        {
            teachercode_=std::make_shared<std::string>(r["teachercode"].as<std::string>());
        }
        if(!r["studentcode"].isNull())
        {
            studentcode_=std::make_shared<std::string>(r["studentcode"].as<std::string>());
        }
        if(!r["objective"].isNull())
        {
            objective_=std::make_shared<std::string>(r["objective"].as<std::string>());
        }
        if(!r["syllabus"].isNull())
        {
            syllabus_=std::make_shared<std::string>(r["syllabus"].as<std::string>());
        }
        if(!r["evaluationmethod"].isNull())
        {
            evaluationmethod_=std::make_shared<std::string>(r["evaluationmethod"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            courseId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            ownerId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            code_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            teachercode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            studentcode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            objective_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            syllabus_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            evaluationmethod_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Course::Course(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            ownerId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());

        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            code_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());

        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            teachercode_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());

        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            studentcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());

        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            objective_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());

        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            syllabus_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());

        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            evaluationmethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());

        }
    }
}

Course::Course(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("owner_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["owner_id"].isNull())
        {
            ownerId_=std::make_shared<uint32_t>((uint32_t)pJson["owner_id"].asUInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("code"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["code"].isNull())
        {
            code_=std::make_shared<std::string>(pJson["code"].asString());
        }
    }
    if(pJson.isMember("teachercode"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["teachercode"].isNull())
        {
            teachercode_=std::make_shared<std::string>(pJson["teachercode"].asString());
        }
    }
    if(pJson.isMember("studentcode"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["studentcode"].isNull())
        {
            studentcode_=std::make_shared<std::string>(pJson["studentcode"].asString());
        }
    }
    if(pJson.isMember("objective"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["objective"].isNull())
        {
            objective_=std::make_shared<std::string>(pJson["objective"].asString());
        }
    }
    if(pJson.isMember("syllabus"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["syllabus"].isNull())
        {
            syllabus_=std::make_shared<std::string>(pJson["syllabus"].asString());
        }
    }
    if(pJson.isMember("evaluationmethod"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["evaluationmethod"].isNull())
        {
            evaluationmethod_=std::make_shared<std::string>(pJson["evaluationmethod"].asString());
        }
    }
}

void Course::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            ownerId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            code_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            teachercode_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            studentcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            objective_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            syllabus_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            evaluationmethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}
                                                                    
void Course::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("course_id"))
    {
        if(!pJson["course_id"].isNull())
        {
            courseId_=std::make_shared<uint32_t>((uint32_t)pJson["course_id"].asUInt64());
        }
    }
    if(pJson.isMember("owner_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["owner_id"].isNull())
        {
            ownerId_=std::make_shared<uint32_t>((uint32_t)pJson["owner_id"].asUInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("code"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["code"].isNull())
        {
            code_=std::make_shared<std::string>(pJson["code"].asString());
        }
    }
    if(pJson.isMember("teachercode"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["teachercode"].isNull())
        {
            teachercode_=std::make_shared<std::string>(pJson["teachercode"].asString());
        }
    }
    if(pJson.isMember("studentcode"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["studentcode"].isNull())
        {
            studentcode_=std::make_shared<std::string>(pJson["studentcode"].asString());
        }
    }
    if(pJson.isMember("objective"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["objective"].isNull())
        {
            objective_=std::make_shared<std::string>(pJson["objective"].asString());
        }
    }
    if(pJson.isMember("syllabus"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["syllabus"].isNull())
        {
            syllabus_=std::make_shared<std::string>(pJson["syllabus"].asString());
        }
    }
    if(pJson.isMember("evaluationmethod"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["evaluationmethod"].isNull())
        {
            evaluationmethod_=std::make_shared<std::string>(pJson["evaluationmethod"].asString());
        }
    }
}

const uint32_t &Course::getValueOfCourseId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(courseId_)
        return *courseId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Course::getCourseId() const noexcept
{
    return courseId_;
}
void Course::setCourseId(const uint32_t &pCourseId) noexcept
{
    courseId_ = std::make_shared<uint32_t>(pCourseId);
    dirtyFlag_[0] = true;
}



const typename Course::PrimaryKeyType & Course::getPrimaryKey() const
{
    assert(courseId_);
    return *courseId_;
}

const uint32_t &Course::getValueOfOwnerId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(ownerId_)
        return *ownerId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &Course::getOwnerId() const noexcept
{
    return ownerId_;
}
void Course::setOwnerId(const uint32_t &pOwnerId) noexcept
{
    ownerId_ = std::make_shared<uint32_t>(pOwnerId);
    dirtyFlag_[1] = true;
}




const std::string &Course::getValueOfName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Course::getName() const noexcept
{
    return name_;
}
void Course::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[2] = true;
}
void Course::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[2] = true;
}




const std::string &Course::getValueOfCode() const noexcept
{
    const static std::string defaultValue = std::string();
    if(code_)
        return *code_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Course::getCode() const noexcept
{
    return code_;
}
void Course::setCode(const std::string &pCode) noexcept
{
    code_ = std::make_shared<std::string>(pCode);
    dirtyFlag_[3] = true;
}
void Course::setCode(std::string &&pCode) noexcept
{
    code_ = std::make_shared<std::string>(std::move(pCode));
    dirtyFlag_[3] = true;
}




const std::string &Course::getValueOfTeachercode() const noexcept
{
    const static std::string defaultValue = std::string();
    if(teachercode_)
        return *teachercode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Course::getTeachercode() const noexcept
{
    return teachercode_;
}
void Course::setTeachercode(const std::string &pTeachercode) noexcept
{
    teachercode_ = std::make_shared<std::string>(pTeachercode);
    dirtyFlag_[4] = true;
}
void Course::setTeachercode(std::string &&pTeachercode) noexcept
{
    teachercode_ = std::make_shared<std::string>(std::move(pTeachercode));
    dirtyFlag_[4] = true;
}




const std::string &Course::getValueOfStudentcode() const noexcept
{
    const static std::string defaultValue = std::string();
    if(studentcode_)
        return *studentcode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Course::getStudentcode() const noexcept
{
    return studentcode_;
}
void Course::setStudentcode(const std::string &pStudentcode) noexcept
{
    studentcode_ = std::make_shared<std::string>(pStudentcode);
    dirtyFlag_[5] = true;
}
void Course::setStudentcode(std::string &&pStudentcode) noexcept
{
    studentcode_ = std::make_shared<std::string>(std::move(pStudentcode));
    dirtyFlag_[5] = true;
}




const std::string &Course::getValueOfObjective() const noexcept
{
    const static std::string defaultValue = std::string();
    if(objective_)
        return *objective_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Course::getObjective() const noexcept
{
    return objective_;
}
void Course::setObjective(const std::string &pObjective) noexcept
{
    objective_ = std::make_shared<std::string>(pObjective);
    dirtyFlag_[6] = true;
}
void Course::setObjective(std::string &&pObjective) noexcept
{
    objective_ = std::make_shared<std::string>(std::move(pObjective));
    dirtyFlag_[6] = true;
}


void Course::setObjectiveToNull() noexcept
{
    objective_.reset();
    dirtyFlag_[6] = true;
}


const std::string &Course::getValueOfSyllabus() const noexcept
{
    const static std::string defaultValue = std::string();
    if(syllabus_)
        return *syllabus_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Course::getSyllabus() const noexcept
{
    return syllabus_;
}
void Course::setSyllabus(const std::string &pSyllabus) noexcept
{
    syllabus_ = std::make_shared<std::string>(pSyllabus);
    dirtyFlag_[7] = true;
}
void Course::setSyllabus(std::string &&pSyllabus) noexcept
{
    syllabus_ = std::make_shared<std::string>(std::move(pSyllabus));
    dirtyFlag_[7] = true;
}


void Course::setSyllabusToNull() noexcept
{
    syllabus_.reset();
    dirtyFlag_[7] = true;
}


const std::string &Course::getValueOfEvaluationmethod() const noexcept
{
    const static std::string defaultValue = std::string();
    if(evaluationmethod_)
        return *evaluationmethod_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Course::getEvaluationmethod() const noexcept
{
    return evaluationmethod_;
}
void Course::setEvaluationmethod(const std::string &pEvaluationmethod) noexcept
{
    evaluationmethod_ = std::make_shared<std::string>(pEvaluationmethod);
    dirtyFlag_[8] = true;
}
void Course::setEvaluationmethod(std::string &&pEvaluationmethod) noexcept
{
    evaluationmethod_ = std::make_shared<std::string>(std::move(pEvaluationmethod));
    dirtyFlag_[8] = true;
}


void Course::setEvaluationmethodToNull() noexcept
{
    evaluationmethod_.reset();
    dirtyFlag_[8] = true;
}


void Course::updateId(const uint64_t id)
{
    courseId_ = std::make_shared<uint32_t>(static_cast<uint32_t>(id));
}

const std::vector<std::string> &Course::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "owner_id",
        "name",
        "code",
        "teachercode",
        "studentcode",
        "objective",
        "syllabus",
        "evaluationmethod"
    };
    return inCols;
}

void Course::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOwnerId())
        {
            binder << getValueOfOwnerId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCode())
        {
            binder << getValueOfCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTeachercode())
        {
            binder << getValueOfTeachercode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStudentcode())
        {
            binder << getValueOfStudentcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getObjective())
        {
            binder << getValueOfObjective();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSyllabus())
        {
            binder << getValueOfSyllabus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getEvaluationmethod())
        {
            binder << getValueOfEvaluationmethod();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Course::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Course::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOwnerId())
        {
            binder << getValueOfOwnerId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCode())
        {
            binder << getValueOfCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTeachercode())
        {
            binder << getValueOfTeachercode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStudentcode())
        {
            binder << getValueOfStudentcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getObjective())
        {
            binder << getValueOfObjective();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSyllabus())
        {
            binder << getValueOfSyllabus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getEvaluationmethod())
        {
            binder << getValueOfEvaluationmethod();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Course::toJson() const
{
    Json::Value ret;
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getOwnerId())
    {
        ret["owner_id"]=getValueOfOwnerId();
    }
    else
    {
        ret["owner_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getCode())
    {
        ret["code"]=getValueOfCode();
    }
    else
    {
        ret["code"]=Json::Value();
    }
    if(getTeachercode())
    {
        ret["teachercode"]=getValueOfTeachercode();
    }
    else
    {
        ret["teachercode"]=Json::Value();
    }
    if(getStudentcode())
    {
        ret["studentcode"]=getValueOfStudentcode();
    }
    else
    {
        ret["studentcode"]=Json::Value();
    }
    if(getObjective())
    {
        ret["objective"]=getValueOfObjective();
    }
    else
    {
        ret["objective"]=Json::Value();
    }
    if(getSyllabus())
    {
        ret["syllabus"]=getValueOfSyllabus();
    }
    else
    {
        ret["syllabus"]=Json::Value();
    }
    if(getEvaluationmethod())
    {
        ret["evaluationmethod"]=getValueOfEvaluationmethod();
    }
    else
    {
        ret["evaluationmethod"]=Json::Value();
    }
    return ret;
}

Json::Value Course::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCourseId())
            {
                ret[pMasqueradingVector[0]]=getValueOfCourseId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getOwnerId())
            {
                ret[pMasqueradingVector[1]]=getValueOfOwnerId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[2]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCode())
            {
                ret[pMasqueradingVector[3]]=getValueOfCode();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTeachercode())
            {
                ret[pMasqueradingVector[4]]=getValueOfTeachercode();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getStudentcode())
            {
                ret[pMasqueradingVector[5]]=getValueOfStudentcode();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getObjective())
            {
                ret[pMasqueradingVector[6]]=getValueOfObjective();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getSyllabus())
            {
                ret[pMasqueradingVector[7]]=getValueOfSyllabus();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getEvaluationmethod())
            {
                ret[pMasqueradingVector[8]]=getValueOfEvaluationmethod();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCourseId())
    {
        ret["course_id"]=getValueOfCourseId();
    }
    else
    {
        ret["course_id"]=Json::Value();
    }
    if(getOwnerId())
    {
        ret["owner_id"]=getValueOfOwnerId();
    }
    else
    {
        ret["owner_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getCode())
    {
        ret["code"]=getValueOfCode();
    }
    else
    {
        ret["code"]=Json::Value();
    }
    if(getTeachercode())
    {
        ret["teachercode"]=getValueOfTeachercode();
    }
    else
    {
        ret["teachercode"]=Json::Value();
    }
    if(getStudentcode())
    {
        ret["studentcode"]=getValueOfStudentcode();
    }
    else
    {
        ret["studentcode"]=Json::Value();
    }
    if(getObjective())
    {
        ret["objective"]=getValueOfObjective();
    }
    else
    {
        ret["objective"]=Json::Value();
    }
    if(getSyllabus())
    {
        ret["syllabus"]=getValueOfSyllabus();
    }
    else
    {
        ret["syllabus"]=Json::Value();
    }
    if(getEvaluationmethod())
    {
        ret["evaluationmethod"]=getValueOfEvaluationmethod();
    }
    else
    {
        ret["evaluationmethod"]=Json::Value();
    }
    return ret;
}

bool Course::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, true))
            return false;
    }
    if(pJson.isMember("owner_id"))
    {
        if(!validJsonOfField(1, "owner_id", pJson["owner_id"], err, true))
            return false;
    }
    else
    {
        err="The owner_id column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("code"))
    {
        if(!validJsonOfField(3, "code", pJson["code"], err, true))
            return false;
    }
    else
    {
        err="The code column cannot be null";
        return false;
    }
    if(pJson.isMember("teachercode"))
    {
        if(!validJsonOfField(4, "teachercode", pJson["teachercode"], err, true))
            return false;
    }
    else
    {
        err="The teachercode column cannot be null";
        return false;
    }
    if(pJson.isMember("studentcode"))
    {
        if(!validJsonOfField(5, "studentcode", pJson["studentcode"], err, true))
            return false;
    }
    else
    {
        err="The studentcode column cannot be null";
        return false;
    }
    if(pJson.isMember("objective"))
    {
        if(!validJsonOfField(6, "objective", pJson["objective"], err, true))
            return false;
    }
    if(pJson.isMember("syllabus"))
    {
        if(!validJsonOfField(7, "syllabus", pJson["syllabus"], err, true))
            return false;
    }
    if(pJson.isMember("evaluationmethod"))
    {
        if(!validJsonOfField(8, "evaluationmethod", pJson["evaluationmethod"], err, true))
            return false;
    }
    return true;
}
bool Course::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Course::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("course_id"))
    {
        if(!validJsonOfField(0, "course_id", pJson["course_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("owner_id"))
    {
        if(!validJsonOfField(1, "owner_id", pJson["owner_id"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(2, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("code"))
    {
        if(!validJsonOfField(3, "code", pJson["code"], err, false))
            return false;
    }
    if(pJson.isMember("teachercode"))
    {
        if(!validJsonOfField(4, "teachercode", pJson["teachercode"], err, false))
            return false;
    }
    if(pJson.isMember("studentcode"))
    {
        if(!validJsonOfField(5, "studentcode", pJson["studentcode"], err, false))
            return false;
    }
    if(pJson.isMember("objective"))
    {
        if(!validJsonOfField(6, "objective", pJson["objective"], err, false))
            return false;
    }
    if(pJson.isMember("syllabus"))
    {
        if(!validJsonOfField(7, "syllabus", pJson["syllabus"], err, false))
            return false;
    }
    if(pJson.isMember("evaluationmethod"))
    {
        if(!validJsonOfField(8, "evaluationmethod", pJson["evaluationmethod"], err, false))
            return false;
    }
    return true;
}
bool Course::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Course::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson, 
                              std::string &err, 
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }        
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 40)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 40)";
                return false;               
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 75)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 75)";
                return false;               
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;               
            }

            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 45)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 45)";
                return false;               
            }

            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
